Build docker image:
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSOWRD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
